package br.com.flowbiz.onsite

/**
 * Pure UTM ingestion rules behind the [Flowbiz.handleLink] capture
 * (SPEC §11.1): a port of the web tag's `onsite-core`
 * `Url.getQueryParameters` plus the allowlist walk and `{...stored,
 * ...current}` merge of `setUtmNavigationContext`, quirks included. Pinned
 * byte for byte by `shared/utm-links/vectors.json`, which is generated by
 * running the web code itself.
 *
 * Deliberately separate from [RecoveryLinkParser]: nearly every rule
 * differs (query extent, `=` split, key decoding, first- vs last-wins), and
 * the recovery vectors pin the recovery decoder's own behavior.
 *
 * ## Web quirks reproduced on purpose (SPEC §11.1 item 1)
 * - The query is the text between the first `?` and the next `?` (JS
 *   `url.split('?')[1]`), cut at the first `/#`, then at the first `#`:
 *   a query inside a hash route (`/#/cart?utm_source=x`) is read.
 * - JS `split` semantics: empty parts are kept, trailing ones included —
 *   `utm_source==x` has an empty value, `=utm_source` an empty key.
 * - Keys are raw: not decoded, not lowercased. A pair without `=` yields
 *   the string `"undefined"` (`decodeURIComponent(undefined)`); parts after
 *   a second `=` are dropped.
 * - The last assignment of a key wins, an empty one included — so a later
 *   empty value (or empty `utm_flow_params` segment) erases an earlier one
 *   *before* the non-empty filter drops it.
 *
 * Operates on UTF-16 code units, exactly like JS strings (a combining mark
 * after a separator never glues to it; see the
 * `combining_mark_after_separators` vector). Never throws for any input
 * string (fuzzed in `UtmLinkParserTest`); callers still run it inside the
 * SPEC §3 catch-all.
 */
internal object UtmLinkParser {

    /**
     * SPEC §11.1 allowlist in web order (`Url.UtmParameters`): the current
     * set is collected in this order, and nothing else is ever kept.
     */
    val ALLOWLIST: List<String> = listOf(
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_journey",
        "utm_journey_channel",
        "utm_journey_type",
        "utm_step_id",
        "utm_journey_version",
        "utm_journey_instance",
    )

    /** Piped `step|version|instance` (web `pipedUtmParametersMap`); never kept itself. */
    private const val FLOW_PARAMS = "utm_flow_params"
    private val FLOW_PARAMS_KEYS = listOf("utm_step_id", "utm_journey_version", "utm_journey_instance")

    /**
     * The link's allowlisted UTMs with non-empty values, in [ALLOWLIST]
     * order — the web's `currentUtms`. Empty for a link without a query.
     */
    fun extract(url: String): List<Pair<String, String>> {
        val params = queryParameters(url)
        return ALLOWLIST.mapNotNull { key ->
            params[key]?.takeIf { it.isNotEmpty() }?.let { key to it }
        }
    }

    /**
     * Web `{...stored, ...current}`: stored keys keep their position and
     * take the new value, new keys are appended in [current]'s order. A merge
     * never removes a key.
     */
    fun merge(
        stored: List<Pair<String, String>>,
        current: List<Pair<String, String>>,
    ): List<Pair<String, String>> {
        val merged = stored.toMutableList()
        for (pair in current) {
            val index = merged.indexOfFirst { it.first == pair.first }
            if (index >= 0) merged[index] = pair else merged += pair
        }
        return merged
    }

    /** `context.utm`: `JSON.stringify` of the pairs, compact, in pair order (SPEC §11.1 item 5). */
    fun render(pairs: List<Pair<String, String>>): String = CanonicalJson.renderStringPairs(pairs)

    /**
     * Web `Url.getQueryParameters` with piped expansion: every key of the
     * query, the last assignment winning. Kotlin's `split(Char)` keeps
     * empty parts, trailing ones included — JS semantics (unlike Java's
     * regex `String.split`).
     */
    private fun queryParameters(url: String): Map<String, String> {
        val start = url.indexOf('?')
        if (start < 0) return emptyMap()
        val next = url.indexOf('?', start + 1)
        val query = url.substring(start + 1, if (next < 0) url.length else next)
            .cutAt("/#")
            .cutAt("#")
        val params = HashMap<String, String>()
        for (segment in query.split('&')) {
            val parts = segment.split('=')
            val key = parts[0]
            if (key.isEmpty()) continue
            val value = if (parts.size < 2) "undefined" else decodeURIComponentOrRaw(parts[1])
            if (key == FLOW_PARAMS) {
                // Only indices below min(3, n) are assigned: a missing
                // segment leaves its key untouched, an empty one sets "".
                val values = value.split('|')
                for (i in 0 until minOf(FLOW_PARAMS_KEYS.size, values.size)) {
                    params[FLOW_PARAMS_KEYS[i]] = values[i]
                }
            } else {
                params[key] = value
            }
        }
        return params
    }

    private fun String.cutAt(marker: String): String {
        val index = indexOf(marker)
        return if (index < 0) this else substring(0, index)
    }

    /**
     * ECMA-262 `decodeURIComponent` (the `Decode` operation with an empty
     * reserved set), returning [value] unchanged on any `URIError` — the
     * web's `try { decodeURIComponent(pair[1]) } catch { pair[1] }`:
     * - `%` must be followed by two hex digits, either case;
     * - a byte ≥ 0x80 must lead a well-formed UTF-8 sequence whose
     *   continuation bytes are `%XX` escapes too — no overlongs, no
     *   surrogates (U+D800–DFFF), nothing above U+10FFFF;
     * - `+` is not a space; every escape decodes, reserved ones included
     *   (`%26` `%3D` `%23` `%25`); raw characters, non-ASCII included, pass
     *   through untouched.
     *
     * Hand-rolled on purpose: [RecoveryLinkParser]'s decoder substitutes
     * U+FFFD for invalid UTF-8 (the web keeps the raw value), and a
     * `CharsetDecoder` would leave strictness to the runtime — this way the
     * JVM (tests) and ART agree by construction.
     */
    fun decodeURIComponentOrRaw(value: String): String {
        if (value.indexOf('%') < 0) return value
        val out = StringBuilder(value.length)
        var k = 0
        while (k < value.length) {
            val c = value[k]
            if (c != '%') {
                out.append(c)
                k++
                continue
            }
            val lead = escapedByte(value, k) ?: return value
            k += 3
            if (lead < 0x80) {
                out.append(lead.toChar())
                continue
            }
            // Sequence length from the lead byte's high bits; a continuation
            // byte (10xxxxxx) or 11111xxx as a lead is a URIError.
            val length = when {
                (lead and 0xE0) == 0xC0 -> 2
                (lead and 0xF0) == 0xE0 -> 3
                (lead and 0xF8) == 0xF0 -> 4
                else -> return value
            }
            var codePoint = lead and (0xFF ushr (length + 1))
            for (i in 1 until length) {
                val continuation = escapedByte(value, k) ?: return value
                if ((continuation and 0xC0) != 0x80) return value
                codePoint = (codePoint shl 6) or (continuation and 0x3F)
                k += 3
            }
            val minimum = when (length) {
                2 -> 0x80
                3 -> 0x800
                else -> 0x10000
            }
            if (codePoint < minimum || codePoint > 0x10FFFF || codePoint in 0xD800..0xDFFF) return value
            out.appendCodePoint(codePoint)
        }
        return out.toString()
    }

    /** The byte of the `%XX` escape starting at [index], or null when there is none there. */
    private fun escapedByte(value: String, index: Int): Int? {
        if (index + 2 >= value.length || value[index] != '%') return null
        val high = hexValue(value[index + 1])
        val low = hexValue(value[index + 2])
        return if (high < 0 || low < 0) null else (high shl 4) or low
    }

    private fun hexValue(char: Char): Int = when (char) {
        in '0'..'9' -> char - '0'
        in 'a'..'f' -> char - 'a' + 10
        in 'A'..'F' -> char - 'A' + 10
        else -> -1
    }
}
