// UTM ingestion (SPEC §11.1): web `Url.getQueryParameters` +
// `setUtmNavigationContext` parity, pinned byte-for-byte by
// `shared/utm-links/vectors.json` (generated by running the web tag's own
// code — see the README there).
//
// Comparisons are on UTF-8 bytes, never `String ==`: Swift string equality
// is canonical equivalence, so `"=\u{338}"` would equal `"≠"` and a
// combining-mark regression could pass unnoticed.
#if canImport(Testing)
import Foundation
import Testing
#if canImport(JavaScriptCore)
import JavaScriptCore
#endif
@testable import FlowbizOnsite

@Suite struct UtmLinkParserSuite {

    static func vectors() throws -> [String: Any] {
        let url = FixtureSupport.sharedDirectory("utm-links").appendingPathComponent("vectors.json")
        let data = try Data(contentsOf: url)
        guard let root = try JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            throw FixtureSupport.FixtureError("utm-links/vectors.json: root is not an object")
        }
        return root
    }

    /// `context.utm` after one evaluation of `url` over `stored` — the
    /// FlowbizCore evaluation without the store/enabled plumbing.
    private static func evaluate(_ url: String?, over stored: UtmLinkParser.Pairs) -> UtmLinkParser.Pairs {
        UtmLinkParser.merge(stored: stored, current: url.map(UtmLinkParser.extract) ?? [])
    }

    private static func contextUtm(_ pairs: UtmLinkParser.Pairs) -> String? {
        pairs.isEmpty ? nil : UtmLinkParser.render(pairs)
    }

    private static func sameBytes(_ actual: String?, _ expected: String?) -> Bool {
        actual.map { Array($0.utf8) } == expected.map { Array($0.utf8) }
    }

    // MARK: Shared vectors (SPEC §14 drift guard)

    /// A truncated or mis-generated file must fail loudly rather than pass
    /// vacuously on fewer vectors.
    @Test func vectorFileIsComplete() throws {
        let root = try Self.vectors()
        #expect((root["extract"] as? [Any])?.count ?? 0 >= 60)
        #expect((root["sequences"] as? [Any])?.count ?? 0 >= 4)
        #expect(root["envelope"] as? [String: Any] != nil)
    }

    @Test func extractVectorsRenderTheWebContextUtmByteForByte() throws {
        let vectors = try #require(try Self.vectors()["extract"] as? [[String: Any]])
        for vector in vectors {
            let name = vector["name"] as? String ?? "?"
            let url = try #require(vector["url"] as? String, "\(name): url")
            let expected = vector["expected"] as? String // null ⇔ no `utm` key
            let actual = Self.contextUtm(Self.evaluate(url, over: []))
            #expect(
                Self.sameBytes(actual, expected),
                "\(name): got \(actual.debugDescription), web sends \(expected.debugDescription)"
            )
        }
    }

    /// One store carried across steps; `url: null` is an evaluation with no
    /// link (foreground / foreground re-enable).
    @Test func sequenceVectorsCarryTheMergedSetStepToStep() throws {
        let sequences = try #require(try Self.vectors()["sequences"] as? [[String: Any]])
        for sequence in sequences {
            let name = sequence["name"] as? String ?? "?"
            let steps = try #require(sequence["steps"] as? [[String: Any]], "\(name): steps")
            var stored: UtmLinkParser.Pairs = []
            for (index, step) in steps.enumerated() {
                let url = step["url"] as? String
                let expected = step["expected"] as? String
                let merged = Self.evaluate(url, over: stored)
                if !merged.isEmpty { stored = merged } // an empty merge writes nothing
                let actual = Self.contextUtm(merged)
                #expect(
                    Self.sameBytes(actual, expected),
                    "\(name) step \(index): got \(actual.debugDescription), web sends \(expected.debugDescription)"
                )
            }
        }
    }

    /// The outer escaping: `context.utm` is a JSON *string* inside the
    /// canonical envelope, not an object (SPEC §4).
    @Test func envelopeVectorPinsTheOuterStringEscaping() throws {
        let envelope = try #require(try Self.vectors()["envelope"] as? [String: Any])
        let utm = try #require(envelope["utm"] as? String)
        let contextCanonical = try #require(envelope["context_canonical"] as? String)
        #expect(Self.sameBytes(try CanonicalJSON.render(["utm": utm]), contextCanonical))

        // Through the real builder: the rendered context embeds the same pair.
        let entry = EnvelopeBuilder.buildRaw(
            wireName: "cart.sync", dataJSON: "{}", hash: "h", createdAtMillis: 0, sentAtMillis: 0,
            timezone: "-03:00", userId: nil, anonymousId: "a", sessionId: "s", visitCount: 1,
            language: "pt-BR", screen: "1x1", appId: "77777", platform: "ios", sdkVersion: "1.0.0",
            utm: utm
        )
        let renderedContext = try CanonicalJSON.render(try #require(entry["context"]))
        let pair = String(contextCanonical.dropFirst().dropLast()) // `"utm":"…"`
        #expect(renderedContext.utf8.count > pair.utf8.count)
        #expect(renderedContext.contains(pair))
    }

    // MARK: Extraction details beyond the vectors

    @Test func extractReturnsAllowlistOrderedPairs() {
        let pairs = UtmLinkParser.extract("https://store.com/?utm_journey_type=1&utm_source=s&utm_flow_params=A|B|C")
        #expect(pairs.map(\.key) == ["utm_source", "utm_journey_type", "utm_step_id", "utm_journey_version", "utm_journey_instance"])
        #expect(pairs.map(\.value) == ["s", "1", "A", "B", "C"])
    }

    @Test func mergeKeepsStoredPositionsAndAppendsNewKeysInCurrentOrder() {
        let merged = UtmLinkParser.merge(
            stored: [(key: "utm_campaign", value: "c"), (key: "utm_source", value: "s")],
            current: [(key: "utm_source", value: "t"), (key: "utm_medium", value: "m"), (key: "utm_journey", value: "j")]
        )
        #expect(merged.map(\.key) == ["utm_campaign", "utm_source", "utm_medium", "utm_journey"])
        #expect(merged.map(\.value) == ["c", "t", "m", "j"])
        // A merge never removes a key.
        #expect(UtmLinkParser.merge(stored: merged, current: []).count == 4)
    }

    @Test func renderIsCompactJSONInPairOrder() {
        #expect(UtmLinkParser.render([]) == "{}")
        #expect(
            UtmLinkParser.render([(key: "utm_medium", value: "a\"b\\c/\u{7F}\u{2028}"), (key: "utm_source", value: "\u{01}\u{08}")])
                == "{\"utm_medium\":\"a\\\"b\\\\c/\u{7F}\u{2028}\",\"utm_source\":\"\\u0001\\b\"}"
        )
    }

    // MARK: decodeURIComponent (ECMA-262 Decode, empty reserved set)

    @Test func decoderFollowsDecodeURIComponent() {
        let cases: [(String, String)] = [
            ("", ""),
            ("plain", "plain"),
            ("a+b%20c", "a+b c"),                       // '+' is not a space
            ("%26%3D%23%25%2B%2F%3F", "&=#%+/?"),       // reserved characters decode too
            ("%c3%a7%C3%A3", "çã"),                     // either hex case
            ("promoção%20", "promoção "),                // raw non-ASCII passes through
            ("%F0%9F%98%80", "😀"),
            ("%F4%8F%BF%BF", "\u{10FFFF}"),
            ("%EF%BF%BE", "\u{FFFE}"),                   // noncharacters are valid scalars
            ("%00", "\u{0}"),
            ("%7F", "\u{7F}"),
            // Failures keep the raw input whole.
            ("%", "%"),
            ("100%", "100%"),
            ("%2", "%2"),
            ("%zz", "%zz"),
            ("%2g", "%2g"),
            ("%C3", "%C3"),                             // truncated sequence
            ("ok%20then%C3", "ok%20then%C3"),
            ("%C3é", "%C3é"),                           // continuation must be an escape
            ("%C3%41", "%C3%41"),                       // bad continuation byte
            ("%80", "%80"),                             // lone continuation byte
            ("%A9", "%A9"),                             // removingPercentEncoding yields U+FFFD here (macOS 15)
            ("%C0%AF", "%C0%AF"),                       // overlong 2-byte
            ("%C1%BF", "%C1%BF"),
            ("%E0%80%80", "%E0%80%80"),                 // overlong 3-byte
            ("%F0%80%80%80", "%F0%80%80%80"),           // overlong 4-byte
            ("%ED%A0%80", "%ED%A0%80"),                 // UTF-16 surrogate
            ("%ED%BF%BF", "%ED%BF%BF"),
            ("%F4%90%80%80", "%F4%90%80%80"),           // above U+10FFFF
            ("%F5%80%80%80", "%F5%80%80%80"),
            ("%F8%80%80%80%80", "%F8%80%80%80%80"),     // 5-byte lead
            ("%FF", "%FF"),
        ]
        for (input, expected) in cases {
            let actual = UtmLinkParser.decodeURIComponentOrRaw(input)
            #expect(Self.sameBytes(actual, expected), "\(input.debugDescription) → \(actual.debugDescription)")
        }
    }

    #if canImport(JavaScriptCore)
    /// Differential check against a real JavaScript engine's
    /// `decodeURIComponent` (the web tag's decoder is the browser built-in;
    /// JavaScriptCore is Safari's): every 1- and 2-escape byte sequence
    /// exhaustively, then seeded random escape/raw mixes. `null` = the JS
    /// call throws, where the port keeps the raw input.
    @Test func decoderAgreesWithTheJavaScriptEngine() throws {
        let context = try #require(JSContext())
        context.evaluateScript("function d(s) { try { return decodeURIComponent(s) } catch (e) { return null } }")
        let decode = try #require(context.objectForKeyedSubscript("d"))
        func check(_ input: String) {
            let result = decode.call(withArguments: [input])
            let web = (result?.isNull ?? true) ? input : result?.toString()
            let port = UtmLinkParser.decodeURIComponentOrRaw(input)
            #expect(Self.sameBytes(port, web), "\(input.debugDescription): port \(port.debugDescription), JS \(web.debugDescription)")
        }
        func escape(_ byte: UInt64) -> String { String(format: "%%%02X", Int(byte & 0xFF)) }

        for first in 0..<256 {
            check(escape(UInt64(first)))
        }
        for first in 0x80..<0x100 {
            for second in 0..<256 {
                check(escape(UInt64(first)) + escape(UInt64(second)))
            }
        }
        let leads: [UInt64] = [0xC0, 0xC2, 0xDF, 0xE0, 0xE1, 0xED, 0xEE, 0xEF, 0xF0, 0xF1, 0xF4, 0xF5, 0xF8]
        let tails: [UInt64] = [0x00, 0x41, 0x7F, 0x80, 0x8F, 0x90, 0x9F, 0xA0, 0xBF, 0xC0, 0xFF]
        let raws = ["a", "+", " ", "%", "%4", "%g1", "é", "😀", "\u{338}", "|", "="]
        var generator = SplitMix64(seed: 20260923)
        for _ in 0..<5_000 {
            var input = ""
            for _ in 0..<(Int(generator.next() % 5) + 1) {
                switch generator.next() % 4 {
                case 0: input += escape(leads[Int(generator.next() % UInt64(leads.count))])
                case 1: input += escape(tails[Int(generator.next() % UInt64(tails.count))])
                case 2: input += escape(generator.next())
                default: input += raws[Int(generator.next() % UInt64(raws.count))]
                }
            }
            check(input)
        }
    }
    #endif

    // MARK: Never-throw (SPEC §3) + backend invariants

    /// Seeded fuzz over a hostile alphabet (every delimiter the extractor
    /// cuts on, escapes, pipes, non-ASCII and combining marks). Must never
    /// trap; the output only ever holds allowlisted keys (never
    /// `utm_flow_params`), each once, in allowlist order, with non-empty
    /// values, and renders to a JSON object of strings.
    @Test func hostileLinksNeverTrapAndOnlyYieldAllowlistedNonEmptyKeys() throws {
        let alphabet = [
            "?", "#", "/", "&", "=", "%", "|", "+", "0", "7", "a", "F", "C3", "A9", "%7C", "%3D", "%26",
            "ç", "😀", "\u{338}", "\u{301}", " ", "/#", "utm_source", "utm_medium", "utm_campaign",
            "utm_flow_params", "utm_step_id", "utm_journey_instance", "UTM_SOURCE", "utm_term",
        ]
        var generator = SplitMix64(seed: 20260911)
        var stored: UtmLinkParser.Pairs = []
        for _ in 0..<2_000 {
            var url = generator.next() % 2 == 0 ? "https://store.com/" : ""
            for _ in 0..<Int(generator.next() % 24) {
                url += alphabet[Int(generator.next() % UInt64(alphabet.count))]
            }
            let current = UtmLinkParser.extract(url)
            let keys = current.map(\.key)
            #expect(Set(keys).count == keys.count)
            #expect(keys == UtmLinkParser.allowlist.filter(keys.contains))
            #expect(!keys.contains("utm_flow_params"))
            #expect(current.allSatisfy { !$0.value.isEmpty })

            stored = UtmLinkParser.merge(stored: stored, current: current)
            let rendered = UtmLinkParser.render(stored)
            let parsed = try JSONSerialization.jsonObject(with: Data(rendered.utf8)) as? [String: String]
            #expect(parsed?.count == stored.count, "\(rendered.debugDescription)")
        }
    }
}
#endif
